In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [10]:
np.arange(10,51,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [11]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

In [12]:
np.linspace(0,15,10)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        , 11.66666667, 13.33333333, 15.        ])

In [13]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.ones([4,8])

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
np.zeros(4)

array([0., 0., 0., 0.])

In [16]:
np.zeros([5,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Random Generator

In [19]:
np.random.random(10)

array([0.03969715, 0.66462092, 0.11740278, 0.43037787, 0.13559306,
       0.91433896, 0.25784149, 0.41340767, 0.56269924, 0.31713129])

In [20]:
np.random.random([2,3])

array([[0.6970178 , 0.19789068, 0.28210779],
       [0.58981975, 0.49290958, 0.10091161]])

In [21]:
np.random.randint(0,10)

9

In [22]:
np.random.seed(42)

arr1=np.random.randint(5,100,(4,6))

In [23]:
arr1

array([[56, 97, 19, 76, 65, 25],
       [87, 91, 79, 79, 92, 28],
       [ 7, 26, 57,  6, 92, 34],
       [42,  6, 68, 64, 25, 37]])

In [24]:
arr1.reshape(2,12)

array([[56, 97, 19, 76, 65, 25, 87, 91, 79, 79, 92, 28],
       [ 7, 26, 57,  6, 92, 34, 42,  6, 68, 64, 25, 37]])

In [25]:
arr1_reshape=arr1.reshape(3,8)
arr1_reshape

array([[56, 97, 19, 76, 65, 25, 87, 91],
       [79, 79, 92, 28,  7, 26, 57,  6],
       [92, 34, 42,  6, 68, 64, 25, 37]])

In [26]:
arr1.shape

(4, 6)

In [27]:
arr1.dtype

dtype('int32')

In [28]:
arr2=np.random.random([2,3])
arr2

array([[0.30424224, 0.52475643, 0.43194502],
       [0.29122914, 0.61185289, 0.13949386]])

In [29]:
arr2.dtype

dtype('float64')

In [30]:
arr1

array([[56, 97, 19, 76, 65, 25],
       [87, 91, 79, 79, 92, 28],
       [ 7, 26, 57,  6, 92, 34],
       [42,  6, 68, 64, 25, 37]])

In [31]:
arr1.max()

97

In [32]:
arr1.argmax()

1

In [33]:
arr1.min()

6

In [34]:
arr1.argmin()

15

## Numpy Operators

In [35]:
arr=np.arange(0,15)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [38]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [40]:
np.square(arr)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [41]:
arr/arr

C:\Users\Leilypour\AppData\Local\Temp\ipykernel_25136\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.])

In [42]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [43]:
np.square(arr)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [78]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06])

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [80]:
arr+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [81]:
arr*20

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200, 220, 240,
       260, 280])

In [82]:
arr/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4])

## Indexing 

In [83]:
arr5=np.arange(15,30)
arr5

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [84]:
arr5[0]

15

In [85]:
arr5[4]

19

In [86]:
arr5[2:7]

array([17, 18, 19, 20, 21])

In [87]:
arr5[:7]

array([15, 16, 17, 18, 19, 20, 21])

In [88]:
arr5[7:]

array([22, 23, 24, 25, 26, 27, 28, 29])

In [89]:
arr6=np.array([[20,21,22,23],[30,31,32,33],[40,41,42,43]])
arr6

array([[20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [90]:
arr6[0,2]

22

In [91]:
arr6[1:]

array([[30, 31, 32, 33],
       [40, 41, 42, 43]])

In [92]:
arr6[1:,2:4]

array([[32, 33],
       [42, 43]])

In [93]:
arr6[:2, :3]

array([[20, 21, 22],
       [30, 31, 32]])

In [94]:
arr6[0,2]

22

In [95]:
arr6[0][2]

22

## Numpy Conditional Selection

In [96]:
arr7=np.random.randint(10,100,(8,9))
arr7

array([[71, 10, 36, 71, 86, 12, 79, 81, 36],
       [18, 71, 46, 60, 53, 33, 88, 68, 41],
       [97, 61, 71, 67, 61, 21, 48, 11, 12],
       [65, 90, 68, 11, 11, 63, 96, 10, 28],
       [11, 62, 53, 99, 41, 79, 41, 77, 64],
       [84, 65, 26, 47, 33, 78, 79, 95, 20],
       [25, 82, 68, 79, 89, 12, 29, 68, 45],
       [28, 99, 76, 28, 29, 80, 61, 42, 49]])

In [97]:
bool_arr=arr7>50

In [98]:
arr7[bool_arr]

array([71, 71, 86, 79, 81, 71, 60, 53, 88, 68, 97, 61, 71, 67, 61, 65, 90,
       68, 63, 96, 62, 53, 99, 79, 77, 64, 84, 65, 78, 79, 95, 82, 68, 79,
       89, 68, 99, 76, 80, 61])

In [99]:
arr7[arr7>50]

array([71, 71, 86, 79, 81, 71, 60, 53, 88, 68, 97, 61, 71, 67, 61, 65, 90,
       68, 63, 96, 62, 53, 99, 79, 77, 64, 84, 65, 78, 79, 95, 82, 68, 79,
       89, 68, 99, 76, 80, 61])

In [100]:
arr7[arr7<30]

array([10, 12, 18, 21, 11, 12, 11, 11, 10, 28, 11, 26, 20, 25, 12, 29, 28,
       28, 29])

In [101]:
arr7[arr7==30]

array([], dtype=int32)

In [112]:
arr7[arr7!=30]

array([71, 10, 36, 71, 86, 12, 79, 81, 36, 18, 71, 46, 60, 53, 33, 88, 68,
       41, 97, 61, 71, 67, 61, 21, 48, 11, 12, 65, 90, 68, 11, 11, 63, 96,
       10, 28, 11, 62, 53, 99, 41, 79, 41, 77, 64, 84, 65, 26, 47, 33, 78,
       79, 95, 20, 25, 82, 68, 79, 89, 12, 29, 68, 45, 28, 99, 76, 28, 29,
       80, 61, 42, 49])

In [113]:
arr7

array([[71, 10, 36, 71, 86, 12, 79, 81, 36],
       [18, 71, 46, 60, 53, 33, 88, 68, 41],
       [97, 61, 71, 67, 61, 21, 48, 11, 12],
       [65, 90, 68, 11, 11, 63, 96, 10, 28],
       [11, 62, 53, 99, 41, 79, 41, 77, 64],
       [84, 65, 26, 47, 33, 78, 79, 95, 20],
       [25, 82, 68, 79, 89, 12, 29, 68, 45],
       [28, 99, 76, 28, 29, 80, 61, 42, 49]])

In [114]:
arr7.mean()

54.083333333333336

In [115]:
arr7.var()

714.4930555555555

In [116]:
arr7.std()

26.730002909755836

## Sorting

In [126]:
arr8=np.random.randint(10,1000,100)

In [127]:
arr8

array([ 38, 174, 431, 348, 657, 505, 374, 842, 351, 509, 666, 520, 336,
       226, 310, 141, 813,  79, 261, 424, 796, 454, 885, 191, 176, 100,
       723, 867, 540,  48, 135, 460, 182, 662, 763, 229, 647,  67, 669,
       485, 465, 838, 904, 370, 944,  10, 396, 982, 357, 199, 514, 200,
       517, 378, 418, 833, 938, 943, 126, 143,  67, 565, 694, 681, 182,
       838, 824, 158,  89, 895, 222, 212, 773, 238, 685, 236, 668, 541,
       450, 411,  56, 242, 314, 535, 152, 424, 522, 382, 575, 895, 268,
       665, 480, 962, 980,  21, 339, 745, 793, 977])

In [128]:
np.sort(arr8)

array([ 10,  21,  38,  48,  56,  67,  67,  79,  89, 100, 126, 135, 141,
       143, 152, 158, 174, 176, 182, 182, 191, 199, 200, 212, 222, 226,
       229, 236, 238, 242, 261, 268, 310, 314, 336, 339, 348, 351, 357,
       370, 374, 378, 382, 396, 411, 418, 424, 424, 431, 450, 454, 460,
       465, 480, 485, 505, 509, 514, 517, 520, 522, 535, 540, 541, 565,
       575, 647, 657, 662, 665, 666, 668, 669, 681, 685, 694, 723, 745,
       763, 773, 793, 796, 813, 824, 833, 838, 838, 842, 867, 885, 895,
       895, 904, 938, 943, 944, 962, 977, 980, 982])

In [129]:
np.argsort(arr8)

array([45, 95,  0, 29, 80, 37, 60, 17, 68, 25, 58, 30, 15, 59, 84, 67,  1,
       24, 64, 32, 23, 49, 51, 71, 70, 13, 35, 75, 73, 81, 18, 90, 14, 82,
       12, 96,  3,  8, 48, 43,  6, 53, 87, 46, 79, 54, 19, 85,  2, 78, 21,
       31, 40, 92, 39,  5,  9, 50, 52, 11, 86, 83, 28, 77, 61, 88, 36,  4,
       33, 91, 10, 76, 38, 63, 74, 62, 26, 97, 34, 72, 98, 20, 16, 66, 55,
       65, 41,  7, 27, 22, 69, 89, 42, 56, 57, 44, 93, 99, 94, 47],
      dtype=int64)

In [131]:
arr8[95]

21

In [132]:
np.sort(arr8)

array([ 10,  21,  38,  48,  56,  67,  67,  79,  89, 100, 126, 135, 141,
       143, 152, 158, 174, 176, 182, 182, 191, 199, 200, 212, 222, 226,
       229, 236, 238, 242, 261, 268, 310, 314, 336, 339, 348, 351, 357,
       370, 374, 378, 382, 396, 411, 418, 424, 424, 431, 450, 454, 460,
       465, 480, 485, 505, 509, 514, 517, 520, 522, 535, 540, 541, 565,
       575, 647, 657, 662, 665, 666, 668, 669, 681, 685, 694, 723, 745,
       763, 773, 793, 796, 813, 824, 833, 838, 838, 842, 867, 885, 895,
       895, 904, 938, 943, 944, 962, 977, 980, 982])

In [133]:
np.sort(arr8)[::-1]

array([982, 980, 977, 962, 944, 943, 938, 904, 895, 895, 885, 867, 842,
       838, 838, 833, 824, 813, 796, 793, 773, 763, 745, 723, 694, 685,
       681, 669, 668, 666, 665, 662, 657, 647, 575, 565, 541, 540, 535,
       522, 520, 517, 514, 509, 505, 485, 480, 465, 460, 454, 450, 431,
       424, 424, 418, 411, 396, 382, 378, 374, 370, 357, 351, 348, 339,
       336, 314, 310, 268, 261, 242, 238, 236, 229, 226, 222, 212, 200,
       199, 191, 182, 182, 176, 174, 158, 152, 143, 141, 135, 126, 100,
        89,  79,  67,  67,  56,  48,  38,  21,  10])

In [143]:
np.argsort(arr8)[::-1]

array([47, 94, 99, 93, 44, 57, 56, 42, 89, 69, 22, 27,  7, 41, 65, 55, 66,
       16, 20, 98, 72, 34, 97, 26, 62, 74, 63, 38, 76, 10, 91, 33,  4, 36,
       88, 61, 77, 28, 83, 86, 11, 52, 50,  9,  5, 39, 92, 40, 31, 21, 78,
        2, 85, 19, 54, 79, 46, 87, 53,  6, 43, 48,  8,  3, 96, 12, 82, 14,
       90, 18, 81, 73, 75, 35, 13, 70, 71, 51, 49, 23, 32, 64, 24,  1, 67,
       84, 59, 15, 30, 58, 25, 68, 17, 60, 37, 80, 29,  0, 95, 45],
      dtype=int64)

In [144]:
arr8.max()

982

In [145]:
arr8.min()

10

In [147]:
arr8.argmax()

47

In [148]:
arr8.argmin()

45

## Dot Product

In [157]:
arr10=np.random.randint(10,20,(3,4))
arr11=np.random.randint(10,20,(3,4))
arr12=np.random.randint(10,20,(4,3))
arr10, arr11

(array([[13, 17, 15, 19],
        [16, 17, 11, 19],
        [17, 12, 16, 12]]),
 array([[16, 11, 19, 15],
        [12, 12, 18, 16],
        [14, 19, 16, 18]]))

In [158]:
arr10*arr11

array([[208, 187, 285, 285],
       [192, 204, 198, 304],
       [238, 228, 256, 216]])

In [159]:
np.dot(arr10,arr12)

array([[1009, 1012,  902],
       [ 987,  988,  895],
       [ 834,  920,  799]])

In [161]:
arr10, arr10.shape

(array([[13, 17, 15, 19],
        [16, 17, 11, 19],
        [17, 12, 16, 12]]),
 (3, 4))

In [162]:
arr10.reshape(4,3)

array([[13, 17, 15],
       [19, 16, 17],
       [11, 19, 17],
       [12, 16, 12]])

## Transpose Matrix

In [163]:
arr10.T

array([[13, 16, 17],
       [17, 17, 12],
       [15, 11, 16],
       [19, 19, 12]])

In [164]:
np.dot(arr10,arr11.T)

array([[ 965,  934, 1087],
       [ 937,  898, 1065],
       [ 888,  828,  938]])

In [166]:
np.dot(arr10,np.reshape(arr11,(4,3)))

array([[1094,  891, 1003],
       [1070,  860, 1004],
       [ 968,  779,  907]])